# Generated by Django 5.0.3 on 2024-03-13 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


