# Generated by Django 5.0.3 on 2024-03-19 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.IntegerField()),
                ('habitudes_alimentaires', models.TextField(blank=True)),
                ('habitudes_de_sommeil', models.TextField(blank=True)),
                ('autres', models.TextField(blank=True)),
                ('situation_medicale', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generer_reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('id_patient', models.IntegerField()),
                ('information', models.TextField()),
                ('message', models.TextField()),
                ('reponse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('id_patient', models.IntegerField()),
                ('meeting_date', models.DateField(default=datetime.date.today)),
                ('discussion', models.TextField()),
                ('bilan', models.TextField()),
                ('key', models.CharField(default='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', max_length=255)),
            ],
        ),
    ]
