# Generated by Django 4.2.1 on 2024-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_user',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
