# Generated by Django 5.0.3 on 2024-03-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_alter_meeting_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='key',
        ),
    ]
