# Generated by Django 5.0.3 on 2024-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_remove_meeting_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='generer_reponse',
            name='key',
        ),
        migrations.AddField(
            model_name='fiche',
            name='autres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='habitudes_alimentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='habitudes_de_sommeil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='id_patient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiche',
            name='situation_medicale',
            field=models.TextField(blank=True),
        ),
    ]
